# Generated by Django 6.0 on 2026-03-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_remove_event_date_remove_event_time_event_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='prize',
            field=models.CharField(default='Certificate', max_length=500),
        ),
    ]
