# Generated by Django 6.0 on 2026-03-07 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_participantprofile_delete_userprofile'),
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='createteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_code', models.CharField(max_length=8, unique=True)),
                ('team_name', models.CharField(max_length=100)),
                ('team_leader', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gitaccount', models.CharField(max_length=100)),
                ('team_members', models.CharField(max_length=500)),
                ('tnc', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.event')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.participantprofile')),
            ],
        ),
        migrations.CreateModel(
            name='jointeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_code', models.CharField(max_length=8)),
                ('team_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gitaccount', models.CharField(max_length=100)),
                ('tnc', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.event')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.participantprofile')),
            ],
        ),
    ]
